services:
  api:
    image: 637811218859.dkr.ecr.eu-central-1.amazonaws.com/esp42:latest
    ports:
      - "80:80"

x-aws-cloudformation:
  Resources:
    ApiTCP80TargetGroup:
      Properties:
        HealthCheckPath: /hello
        Matcher:
          HttpCode: 200-399
