name: deploy_frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '!frontend/package-lock.json'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/esp
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Installing dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Building project
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://esp42.eu --delete
        working-directory: ${{env.working-directory}}
